# Generated by Django 5.2.12 on 2026-04-01 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='lessons.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_goal_xp',
            field=models.IntegerField(default=20, help_text='Daily XP goal set by user'),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Highest streak achieved'),
        ),
        migrations.AddField(
            model_name='user',
            name='native_language',
            field=models.CharField(default='ky', help_text="User's native language", max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='target_language',
            field=models.CharField(default='tr', help_text='Language the user is learning', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='total_lessons_completed',
            field=models.IntegerField(default=0),
        ),
    ]
