# Generated by Codex on 2026-03-26

from django.db import migrations


def backfill_sessions(apps, schema_editor):
    ChatMessage = apps.get_model("ai", "ChatMessage")
    ChatSession = apps.get_model("ai", "ChatSession")

    user_ids = (
        ChatMessage.objects.filter(session__isnull=True)
        .order_by()
        .values_list("user_id", flat=True)
        .distinct()
    )
    for user_id in user_ids:
        session = ChatSession.objects.create(user_id=user_id, title="Legacy")
        ChatMessage.objects.filter(user_id=user_id, session__isnull=True).update(session=session)


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_chatsession_chatmessage_session_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_sessions, migrations.RunPython.noop),
    ]

