# Generated by Django 5.2.8 on 2026-03-28 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_backfill_chatsessions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChatUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_key", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(db_index=True)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_chat_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="ai_dailycha_user_id_251f0b_idx"
                    ),
                    models.Index(
                        fields=["guest_key", "date"],
                        name="ai_dailycha_guest_k_f1fd89_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "date"),
                        name="unique_user_daily_chat_usage",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("guest_key__isnull", False)),
                        fields=("guest_key", "date"),
                        name="unique_guest_daily_chat_usage",
                    ),
                ],
            },
        ),
    ]
