# Generated by Django 5.2.12 on 2026-04-01 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('source_language', models.CharField(help_text="Language of instruction (e.g., 'en')", max_length=10)),
                ('target_language', models.CharField(help_text="Language being learned (e.g., 'tr')", max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description_ky', models.TextField(blank=True, help_text='Description in Kyrgyz', null=True)),
                ('cefr_min', models.CharField(blank=True, help_text="Minimum CEFR level (e.g., 'A1')", max_length=10, null=True)),
                ('cefr_max', models.CharField(blank=True, help_text="Maximum CEFR level (e.g., 'B2')", max_length=10, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title_ky', models.CharField(help_text='Title in Kyrgyz', max_length=255)),
                ('title_target', models.CharField(help_text='Title in target language', max_length=255)),
                ('description_ky', models.TextField(blank=True, help_text='Description in Kyrgyz', null=True)),
                ('icon', models.TextField(blank=True, help_text='Icon name or URL', null=True)),
                ('difficulty', models.CharField(default='beginner', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('estimated_minutes', models.IntegerField(default=0)),
                ('vocabulary_count', models.IntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_categories', to='lessons.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='lessons.course')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ky', models.TextField(blank=True, help_text='Description in Kyrgyz', null=True)),
                ('level', models.CharField(default='a0', max_length=10)),
                ('difficulty', models.CharField(default='beginner', max_length=50)),
                ('duration_min', models.IntegerField(default=5)),
                ('xp_reward', models.IntegerField(default=10)),
                ('grammar_focus', models.TextField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.category')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_type', models.CharField(choices=[('vocab_intro', 'Vocabulary Intro'), ('multiple_choice_translation', 'Multiple Choice Translation'), ('listen_and_choose', 'Listen and Choose'), ('fill_blank', 'Fill in the Blank'), ('reorder_sentence', 'Reorder Sentence'), ('speak_phrase', 'Speak Phrase'), ('dialogue_choice', 'Dialogue Choice'), ('match_pairs', 'Match Pairs'), ('type_translation', 'Type Translation'), ('lesson_summary', 'Lesson Summary')], max_length=50)),
                ('prompt_ky', models.TextField(blank=True, help_text='Prompt in Kyrgyz', null=True)),
                ('instruction_ky', models.TextField(blank=True, help_text='Instruction in Kyrgyz', null=True)),
                ('content', models.JSONField(default=dict, help_text='Structured content for the step')),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('hint_ky', models.TextField(blank=True, help_text='Hint in Kyrgyz', null=True)),
                ('explanation_ky', models.TextField(blank=True, help_text='Explanation in Kyrgyz', null=True)),
                ('xp', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lessons.lesson')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LessonVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_or_phrase_target', models.CharField(max_length=255)),
                ('translation_ky', models.CharField(max_length=255)),
                ('transliteration', models.CharField(blank=True, max_length=255, null=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=50, null=True)),
                ('example_target', models.TextField(blank=True, null=True)),
                ('example_ky', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('difficulty', models.CharField(default='beginner', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='lessons.lesson')),
            ],
            options={
                'verbose_name_plural': 'Lesson vocabularies',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(help_text="'lesson' or 'vocabulary'", max_length=50)),
                ('target_text', models.TextField()),
                ('translation_ky', models.TextField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('strength', models.IntegerField(default=0)),
                ('mistake_count', models.IntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lessonvocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('description_ky', models.TextField(blank=True, help_text='Description in Kyrgyz', null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('cefr_level', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='lessons.course')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lessons.unit'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lessons.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserCategoryProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('completed_lessons', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lessons.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User category progress',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('xp_earned', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User lesson progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User skill progress',
                'unique_together': {('user', 'course', 'skill')},
            },
        ),
    ]
