# Generated by Django 5.2.12 on 2026-04-01 08:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('audio', 'Audio'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='assets/%Y/%m/%d/')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(help_text="ISO language code (e.g., 'en', 'ky', 'ru')", max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_note', models.CharField(blank=True, help_text='Context for translators', max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userlessonprogress',
            options={},
        ),
        migrations.RenameField(
            model_name='userlessonprogress',
            old_name='attempts_count',
            new_name='best_score',
        ),
        migrations.RenameField(
            model_name='userlessonprogress',
            old_name='updated_at',
            new_name='last_activity_at',
        ),
        migrations.RenameField(
            model_name='userlessonprogress',
            old_name='progress_percent',
            new_name='total_attempts',
        ),
        migrations.RenameField(
            model_name='userlessonprogress',
            old_name='xp_earned',
            new_name='total_correct_attempts',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='explanation_ky',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='hint_ky',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='instruction_ky',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='options',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='prompt_ky',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='xp',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='started_at',
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='instruction',
            field=models.TextField(blank=True, help_text='Fallback instructional hint', null=True),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='prompt',
            field=models.TextField(blank=True, help_text='Fallback instruction or question prompt', null=True),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='xp_reward',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='first_started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='total_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='total_xp_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonstep',
            name='step_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('mastered', 'Mastered')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='ContentUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('word', 'Word'), ('phrase', 'Phrase'), ('sentence', 'Sentence')], max_length=20)),
                ('text', models.TextField(blank=True, help_text='Fallback primary text', null=True)),
                ('meaning', models.TextField(blank=True, help_text='Fallback meaning or translation hint', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.asset')),
                ('primary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.asset')),
                ('meaning_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup')),
                ('text_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('hearts_remaining', models.IntegerField(default=5)),
                ('mistakes_count', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('completed_steps_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='last_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lessonsession'),
        ),
        migrations.CreateModel(
            name='StepAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('score', models.IntegerField(default=0)),
                ('client_payload', models.JSONField(help_text='Immutable snapshot of the user interaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.lessonsession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.lessonstep')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('audio_file', models.FileField(upload_to='speech_submissions/%Y/%m/%d/')),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('external_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('feedback_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_submissions', to='lessons.lessonsession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_submissions', to='lessons.lessonstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_submissions', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speech_submission', to='lessons.stepattempt')),
            ],
        ),
        migrations.CreateModel(
            name='StepFillBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_template', models.TextField(help_text="Sentence with placeholders like 'The [[blank]] is on the table'")),
                ('acceptable_answers', models.JSONField(help_text='List of correct strings for the blank(s)')),
                ('source_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.contentunit')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_fill_blank', to='lessons.lessonstep')),
            ],
        ),
        migrations.CreateModel(
            name='StepMatchPairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_match_pairs', to='lessons.lessonstep')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPairItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.CharField(blank=True, max_length=255, null=True)),
                ('right_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('left_content_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.contentunit')),
                ('right_content_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.contentunit')),
                ('step_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='lessons.stepmatchpairs')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StepMultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_multiple_choice', to='lessons.lessonstep')),
            ],
        ),
        migrations.CreateModel(
            name='StepChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Override text or fallback if content_unit is missing', max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('content_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.contentunit')),
                ('step_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lessons.stepmultiplechoice')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StepReorderSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_reorder_sentence', to='lessons.lessonstep')),
            ],
        ),
        migrations.CreateModel(
            name='ReorderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_distractor', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('content_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.contentunit')),
                ('step_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='lessons.stepreordersentence')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StepTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(blank=True, null=True)),
                ('acceptable_answers', models.JSONField(help_text='List of strings that are considered correct translations')),
                ('source_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.contentunit')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_type_translation', to='lessons.lessonstep')),
            ],
        ),
        migrations.CreateModel(
            name='StepSpeakPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.TextField(help_text='The phrase the learner must speak')),
                ('min_score_required', models.IntegerField(default=70, help_text='Minimum AI confidence (0-100) to pass')),
                ('allow_retry', models.BooleanField(default=True)),
                ('reference_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.asset')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_speak_phrase', to='lessons.lessonstep')),
                ('target_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.contentunit')),
                ('target_text_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup')),
            ],
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='instruction_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup'),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='prompt_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup'),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.language')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.translationgroup')),
            ],
            options={
                'unique_together': {('group', 'language')},
            },
        ),
        migrations.CreateModel(
            name='UserContentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exposure_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('mastery_score', models.IntegerField(default=0, help_text='Simple 0-100 mastery rating')),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('content_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lessons.contentunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_unit')},
            },
        ),
    ]
