# Generated by Django 5.2.12 on 2026-04-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_asset_language_translationgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategoryprogress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userskillprogress',
            options={},
        ),
        migrations.AddField(
            model_name='lessonvocabulary',
            name='content_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_references', to='lessons.contentunit'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='content_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_items', to='lessons.contentunit'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='item_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stepattempt',
            name='client_payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='stepchoice',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stepfillblank',
            name='sentence_template',
            field=models.TextField(help_text='The sentence with [[blank]] placeholders'),
        ),
        migrations.AlterField(
            model_name='stepspeakphrase',
            name='min_score_required',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='stepspeakphrase',
            name='target_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steptypetranslation',
            name='acceptable_answers',
            field=models.JSONField(help_text='List of correct translations'),
        ),
        migrations.AlterField(
            model_name='usercontentprogress',
            name='mastery_score',
            field=models.IntegerField(default=0),
        ),
    ]
