# Generated by Django 5.2.12 on 2026-04-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_usercategoryprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='correct_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stepmultiplechoice',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='If true, user can select multiple options (checkbox style)'),
        ),
    ]
