# Generated by Django 5.2.12 on 2026-04-04 09:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_reviewitem_correct_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstep',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, help_text='Difficulty level 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='grammar_note_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup'),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='hint_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup'),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='If true, mistakes do not deplete hearts'),
        ),
        migrations.AddField(
            model_name='stepchoice',
            name='explanation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup'),
        ),
        migrations.AddField(
            model_name='steptypetranslation',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup'),
        ),
        migrations.CreateModel(
            name='StepAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_fallback', models.CharField(blank=True, max_length=255, null=True)),
                ('blank_index', models.PositiveIntegerField(default=0, help_text='Index of the blank in the template (0 for translation)')),
                ('is_primary', models.BooleanField(default=False, help_text='The main answer to show in feedback')),
                ('case_sensitive', models.BooleanField(default=False)),
                ('ignore_punctuation', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('answer_embedding', models.JSONField(blank=True, help_text='Future: Store vector embeddings for AI semantic matching', null=True)),
                ('step_fill_blank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relational_answers', to='lessons.stepfillblank')),
                ('step_type_translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relational_answers', to='lessons.steptypetranslation')),
                ('translation_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.translationgroup')),
            ],
            options={
                'ordering': ['blank_index', 'sort_order', '-is_primary'],
                'indexes': [models.Index(fields=['step_fill_blank', 'blank_index', 'is_primary'], name='lessons_ste_step_fi_283c20_idx'), models.Index(fields=['step_type_translation', 'blank_index', 'is_primary'], name='lessons_ste_step_ty_79a88d_idx'), models.Index(fields=['translation_group'], name='lessons_ste_transla_28dff0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('step_fill_blank__isnull', False), ('step_type_translation__isnull', True)), models.Q(('step_fill_blank__isnull', True), ('step_type_translation__isnull', False)), _connector='OR'), name='stepanswer_exclusive_step_fk'), models.CheckConstraint(condition=models.Q(models.Q(('text_fallback__isnull', True), ('translation_group__isnull', False)), models.Q(('text_fallback__isnull', False), ('translation_group__isnull', True)), models.Q(('text_fallback__isnull', False), ('translation_group__isnull', False)), _connector='OR'), name='stepanswer_content_present'), models.UniqueConstraint(condition=models.Q(('is_primary', True), ('step_fill_blank__isnull', False)), fields=('step_fill_blank', 'blank_index'), name='unique_primary_fill_blank'), models.UniqueConstraint(condition=models.Q(('is_primary', True), ('step_type_translation__isnull', False)), fields=('step_type_translation', 'blank_index'), name='unique_primary_type_translation')],
            },
        ),
    ]
