# Generated by Django 5.2.12 on 2026-04-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessonstep_cefr_level_lessonstep_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepmultiplechoice',
            name='allow_multiple',
        ),
    ]
