# Generated by Django 5.2.12 on 2026-03-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscription",
            "0003_subscriptionplan_remove_subscription_plan_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
