# Generated by Django 5.2.12 on 2026-03-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_subscriptionplan_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
